# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
read_mtbl <- function(path) {
    .Call('mtblr_read_mtbl', PACKAGE = 'mtblr', path)
}

#' @export
mtbl_length <- function(x) {
    .Call('mtblr_mtbl_length', PACKAGE = 'mtblr', x)
}

#' @export
mtbl_map <- function(x) {
    .Call('mtblr_mtbl_map', PACKAGE = 'mtblr', x)
}

#' @export
mtbl_next <- function(x) {
    .Call('mtblr_mtbl_next', PACKAGE = 'mtblr', x)
}

#' @export
mtbl_keys <- function(x) {
    .Call('mtblr_mtbl_keys', PACKAGE = 'mtblr', x)
}

#' @export
mtbl_values <- function(x) {
    .Call('mtblr_mtbl_values', PACKAGE = 'mtblr', x)
}

#' @export
mtbl_get <- function(x, key) {
    .Call('mtblr_mtbl_get', PACKAGE = 'mtblr', x, key)
}

#' @export
mtbl_get_prefix <- function(x, key) {
    .Call('mtblr_mtbl_get_prefix', PACKAGE = 'mtblr', x, key)
}

#' @export
mtbl_iter_close <- function(x) {
    invisible(.Call('mtblr_mtbl_iter_close', PACKAGE = 'mtblr', x))
}

#' @export
close_mtbl <- function(x) {
    invisible(.Call('mtblr_close_mtbl', PACKAGE = 'mtblr', x))
}

